package com.queuedockyard.schemaregistry.service;

import com.queuedockyard.schema.OrderEvent;
import com.queuedockyard.schema.OrderEventV2;
import com.queuedockyard.schema.OrderStatus;
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.kafka.core.KafkaTemplate;
import org.springframework.stereotype.Service;

import java.time.LocalDateTime;
import java.util.UUID;

/**
 * Publishes Avro-serialized order events to Kafka.
 *
 * Notice: OrderEvent and OrderEventV2 are NOT hand-written classes.
 * They are GENERATED by the Avro Maven Plugin from the .avsc files
 * in src/main/avro/ during the Maven build.
 *
 * After running mvn generate-sources (or building the project),
 * IntelliJ will show these classes under target/generated-sources/avro/
 *
 * This means:
 *   - The .avsc file IS the source of truth
 *   - The Java class is just a generated artifact
 *   - Change the .avsc → regenerate → Java class updates automatically
 *   - You never manually keep schema and Java class in sync
 */
@Slf4j
@Service
@RequiredArgsConstructor
public class OrderProducerService {

    /**
     * KafkaTemplate<String, Object> — using Object as value type
     * because we publish both OrderEvent (V1) and OrderEventV2 (V2).
     * The Confluent serializer handles both correctly since it
     * uses the actual runtime type to find the schema.
     */
    private final KafkaTemplate<String, Object> kafkaTemplate;

    @Value("${app.kafka.topics.orders-v1}")
    private String ordersV1Topic;

    @Value("${app.kafka.topics.orders-v2}")
    private String ordersV2Topic;

    /**
     * Publishes a V1 order event using the original schema.
     *
     * On first publish:
     *   Confluent serializer registers the OrderEvent schema
     *   with Schema Registry under subject "schema-orders-v1-value"
     *   and gets back schema ID (e.g. 1).
     *
     * On every publish:
     *   Message bytes = [0x00][0x00][0x00][0x00][0x01][avro binary data]
     *   First 5 bytes = magic byte + schema ID
     *   Consumer reads schema ID → fetches schema → deserializes
     */
    public void publishV1Order(String customerId, double amount, String status) {

        OrderEvent event = OrderEvent.newBuilder()
                .setMessageId(UUID.randomUUID().toString())
                .setOrderId("ORD-" + UUID.randomUUID().toString()
                        .substring(0, 8).toUpperCase())
                .setCustomerId(customerId)
                .setAmount(amount)
                .setStatus(OrderStatus.valueOf(status))
                .setCreatedAt(LocalDateTime.now().toString())
                .build();

        kafkaTemplate.send(ordersV1Topic, event.getOrderId(), event)
                .whenComplete((result, ex) -> {
                    if (ex != null) {
                        log.error("V1 publish failed | reason: {}", ex.getMessage());
                        return;
                    }
                    log.info("V1 published | orderId: {} | schema registered at: {}",
                            event.getOrderId(),
                            "http://localhost:8081/subjects/schema-demo-orders-v1-value/versions");
                });
    }

    /**
     * Publishes a V2 order event using the evolved schema.
     *
     * V2 adds two new fields with defaults:
     *   region        → "UNKNOWN" default
     *   customerEmail → null default
     *
     * Because both new fields have defaults, this is BACKWARD COMPATIBLE.
     * A consumer using the V1 schema can still read V2 messages —
     * it simply ignores the unknown fields.
     * Schema Registry accepts this schema evolution.
     */
    public void publishV2Order(String customerId,
                               double amount,
                               String status,
                               String region,
                               String customerEmail) {

        OrderEventV2 event = OrderEventV2.newBuilder()
                .setMessageId(UUID.randomUUID().toString())
                .setOrderId("ORD-" + UUID.randomUUID().toString()
                        .substring(0, 8).toUpperCase())
                .setCustomerId(customerId)
                .setAmount(amount)
                .setStatus(com.queuedockyard.schema.OrderStatus.valueOf(status))
                .setCreatedAt(LocalDateTime.now().toString())
                .setRegion(region)
                .setCustomerEmail(customerEmail)
                .build();

        kafkaTemplate.send(ordersV2Topic, event.getOrderId(), event)
                .whenComplete((result, ex) -> {
                    if (ex != null) {
                        log.error("V2 publish failed | reason: {}", ex.getMessage());
                        return;
                    }
                    log.info("V2 published | orderId: {} | region: {} | email: {}",
                            event.getOrderId(), region, customerEmail);
                });
    }

}