package com.queuedockyard.exactlyoncedemo.model;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.time.LocalDateTime;

/**
 * Represents a payment event published to Kafka.
 *
 * Why payments for this demo?
 * Payments are the clearest real-world example of why idempotency matters.
 * Processing a payment message twice = charging the customer twice.
 * That is an unacceptable production bug.
 *
 * Key field: messageId
 * This is the idempotency key — a unique ID stamped by the producer
 * on every message. The consumer uses this to detect duplicates.
 *
 * Rule: messageId must be globally unique and stable.
 * UUID generated at publish time works perfectly.
 */
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class PaymentEvent {

    /**
     * The idempotency key.
     * Generated by the producer using UUID.randomUUID().
     * The consumer stores this after processing — if it sees
     * the same messageId again, it skips processing entirely.
     */
    private String messageId;

    /** The order this payment is for. */
    private String orderId;

    /** The customer making the payment. */
    private String customerId;

    /** Payment amount in INR. */
    private Double amount;

    /**
     * Payment method used.
     * Examples: CREDIT_CARD, UPI, NET_BANKING, WALLET
     */
    private String paymentMethod;

    /**
     * Current status of the payment.
     * Examples: INITIATED, SUCCESS, FAILED, REFUNDED
     */
    private String status;

    /** When this event was created — always set at the producer side. */
    private LocalDateTime createdAt;

}